import type { Lesson, Category } from './types';

// Beginner Lessons - Progressive Learning Path
export const beginnerLessons: Lesson[] = [
  // Home Row - Level 1
  {
    id: 'home-row-1',
    title: 'Home Row - Left Hand',
    description: 'Learn the left hand home row keys: A, S, D, F',
    level: 'beginner',
    type: 'letters',
    content: [
      'a a a a a',
      's s s s s',
      'd d d d d',
      'f f f f f',
      'a s d f',
      'f d s a',
      'a s a s',
      'd f d f',
    ],
  },
  {
    id: 'home-row-2',
    title: 'Home Row - Right Hand',
    description: 'Learn the right hand home row keys: J, K, L, ;',
    level: 'beginner',
    type: 'letters',
    content: [
      'j j j j j',
      'k k k k k',
      'l l l l l',
      '; ; ; ; ;',
      'j k l ;',
      '; l k j',
      'j k j k',
      'l ; l ;',
    ],
  },
  {
    id: 'home-row-3',
    title: 'Home Row - Both Hands',
    description: 'Practice using both hands on the home row',
    level: 'beginner',
    type: 'letters',
    content: [
      'a s d f j k l ;',
      'f f j j',
      'd d k k',
      's s l l',
      'a a ; ;',
      'a s d f j k l ;',
      'f j d k s l a ;',
      'a ; s l d k f j',
    ],
  },
  // Home Row Words
  {
    id: 'home-row-words',
    title: 'Home Row Words',
    description: 'Type simple words using home row keys',
    level: 'beginner',
    type: 'words',
    content: [
      'as ad ask lad sad fad',
      'fall pass lass dash',
      'alkali salad alas falls',
      'adds flask asks lads',
      'fad dall dask sall',
    ],
  },
  // Top Row
  {
    id: 'top-row-1',
    title: 'Top Row - Left Hand',
    description: 'Learn the left hand top row keys: Q, W, E, R',
    level: 'beginner',
    type: 'letters',
    content: [
      'q q q q q',
      'w w w w w',
      'e e e e e',
      'r r r r r',
      'q w e r',
      'r e w q',
      'q w q w',
      'e r e r',
    ],
  },
  {
    id: 'top-row-2',
    title: 'Top Row - Right Hand',
    description: 'Learn the right hand top row keys: U, I, O, P',
    level: 'beginner',
    type: 'letters',
    content: [
      'u u u u u',
      'i i i i i',
      'o o o o o',
      'p p p p p',
      'u i o p',
      'p o i u',
      'u i u i',
      'o p o p',
    ],
  },
  {
    id: 'top-row-words',
    title: 'Top Row Words',
    description: 'Type words using top row keys',
    level: 'beginner',
    type: 'words',
    content: [
      'we are our poor',
      'type your write',
      'pure power more',
      'piece quite quote',
      'write poetry power',
    ],
  },
  // Bottom Row
  {
    id: 'bottom-row-1',
    title: 'Bottom Row - Left Hand',
    description: 'Learn the left hand bottom row keys: Z, X, C, V',
    level: 'beginner',
    type: 'letters',
    content: [
      'z z z z z',
      'x x x x x',
      'c c c c c',
      'v v v v v',
      'z x c v',
      'v c x z',
      'z x z x',
      'c v c v',
    ],
  },
  {
    id: 'bottom-row-2',
    title: 'Bottom Row - Right Hand',
    description: 'Learn the right hand bottom row keys: M, ,, ., /',
    level: 'beginner',
    type: 'letters',
    content: [
      'm m m m m',
      ', , , , ,',
      '. . . . .',
      '/ / / / /',
      'm , . /',
      '/ . , m',
      'm , m ,',
      '. / . /',
    ],
  },
  // Combined Practice
  {
    id: 'all-rows-letters',
    title: 'All Rows - Letters',
    description: 'Practice letters from all rows',
    level: 'beginner',
    type: 'letters',
    content: [
      'a q z a q z',
      's w x s w x',
      'd e c d e c',
      'f r v f r v',
      'j u m j u m',
      'k i , k i ,',
      'l o . l o .',
      '; p / ; p /',
    ],
  },
  {
    id: 'simple-sentences',
    title: 'Simple Sentences',
    description: 'Type simple sentences to build fluency',
    level: 'beginner',
    type: 'sentences',
    content: [
      'The cat sat on the mat.',
      'A quick brown fox jumps.',
      'She sells sea shells.',
      'The sun is bright today.',
      'We can see the stars.',
      'He has a red car.',
      'They went to the park.',
      'I like to read books.',
    ],
  },
];

// Intermediate Lessons
export const intermediateLessons: Lesson[] = [
  {
    id: 'common-words',
    title: 'Common Words Practice',
    description: 'Practice typing frequently used words',
    level: 'intermediate',
    type: 'words',
    content: [
      'the and for are but not you all can had her was one our out',
      'day get has him his how its let may new now old see two way',
      'who boy did own say she too use after again before being between',
      'could does found good great house large learn never other should small',
    ],
  },
  {
    id: 'punctuation',
    title: 'Punctuation Mastery',
    description: 'Practice typing with various punctuation marks',
    level: 'intermediate',
    type: 'sentences',
    content: [
      'Hello, how are you today?',
      'I said, "That is wonderful!"',
      'The price is $19.99.',
      'Her email is test@example.com.',
      "It's a beautiful day, isn't it?",
      'The meeting is at 3:30 PM.',
      'We need: milk, eggs, and bread.',
      'She lives in New York, NY.',
    ],
  },
  {
    id: 'numbers',
    title: 'Numbers and Symbols',
    description: 'Practice typing numbers and common symbols',
    level: 'intermediate',
    type: 'sentences',
    content: [
      'The year is 2024.',
      'Call me at 555-1234.',
      'The temperature is 72 degrees.',
      'I scored 95% on the test.',
      'The total is $1,234.56.',
      'Meet me at 7:00 PM.',
      'Room 404 is on floor 4.',
      'Her birthday is 03/15/1990.',
    ],
  },
  {
    id: 'programming-syntax',
    title: 'Programming Syntax',
    description: 'Practice typing code-like patterns',
    level: 'intermediate',
    type: 'sentences',
    content: [
      'function hello() { return "world"; }',
      'const x = [1, 2, 3, 4, 5];',
      'if (x > 0) { console.log(x); }',
      'for (let i = 0; i < 10; i++) {}',
      'const obj = { name: "John", age: 30 };',
      'import { useState } from "react";',
      'export default function App() {}',
      'const arr = arr.map(x => x * 2);',
    ],
  },
];

// Advanced Lessons - Educational Content
export const advancedLessons: Lesson[] = [
  {
    id: 'advanced-speed',
    title: 'Speed Building',
    description: 'Long paragraphs to build typing endurance and speed',
    level: 'advanced',
    type: 'paragraph',
    content: [
      'The quick brown fox jumps over the lazy dog. This classic sentence contains every letter of the alphabet and has been used for typing practice for generations. Mastering this sentence helps ensure you can type any word that comes your way with confidence and speed.',
      'Touch typing is a skill that combines muscle memory with conscious thought. When you first learn, every keystroke requires attention. Over time, your fingers learn the positions and typing becomes automatic, allowing you to focus on your thoughts rather than the mechanics of typing.',
    ],
  },
];

// Educational Categories with Real Content
export const categories: Category[] = [
  {
    id: 'biology',
    name: 'Biology',
    description: 'Learn about living organisms and life processes',
    icon: '🧬',
    paragraphs: [
      'DNA, or deoxyribonucleic acid, is the molecule that carries genetic instructions for all living organisms. Shaped like a twisted ladder, the double helix structure was discovered by Watson and Crick in 1953. This breakthrough revolutionized our understanding of heredity and opened new frontiers in medicine and biotechnology.',
      'Photosynthesis is the process by which plants convert sunlight into chemical energy. Using chlorophyll in their leaves, plants absorb carbon dioxide from the air and water from the soil. Through a series of chemical reactions, they produce glucose and release oxygen, making them essential for life on Earth.',
      'The human heart beats approximately 100,000 times per day, pumping about 2,000 gallons of blood through 60,000 miles of blood vessels. This incredible organ works tirelessly from before birth until death, supplying oxygen and nutrients to every cell while removing waste products.',
      'Evolution through natural selection is the process by which species change over time. First described by Charles Darwin, this mechanism explains how organisms with advantageous traits are more likely to survive and reproduce. Over millions of years, these small changes can lead to entirely new species.',
      'Cells are the basic building blocks of all living things. The human body contains approximately 37 trillion cells, each performing specific functions. Some cells, like neurons, can transmit electrical signals, while others, like red blood cells, transport oxygen throughout the body.',
    ],
  },
  {
    id: 'psychology',
    name: 'Psychology',
    description: 'Explore the human mind and behavior',
    icon: '🧠',
    paragraphs: [
      'Cognitive dissonance occurs when a person holds conflicting beliefs or attitudes. This psychological discomfort motivates people to change their beliefs or behaviors to reduce the tension. Leon Festinger first described this phenomenon in 1957, and it has since become a fundamental concept in understanding human decision-making.',
      'The Stanford Prison Experiment, conducted by Philip Zimbardo in 1971, demonstrated how social roles can influence behavior. College students assigned as guards became increasingly authoritarian, while those assigned as prisoners showed signs of extreme stress. The study revealed powerful effects of situational factors on human behavior.',
      'Memory is not a perfect recording of events but rather a reconstructive process. Each time we recall a memory, we essentially recreate it, which can lead to distortions. This is why eyewitness testimony can be unreliable and why false memories can feel just as real as genuine ones.',
      'Classical conditioning, discovered by Ivan Pavlov, explains how we learn through association. Pavlov observed that dogs would salivate not just when given food, but when they heard the footsteps of the person who fed them. This discovery laid the foundation for behavioral psychology.',
      'Flow state, described by psychologist Mihaly Csikszentmihalyi, is a mental state of complete absorption in an activity. During flow, people lose track of time and feel completely engaged. This state is associated with peak performance and high levels of satisfaction and creativity.',
    ],
  },
  {
    id: 'technology',
    name: 'Technology',
    description: 'Discover innovations shaping our world',
    icon: '💻',
    paragraphs: [
      'Artificial intelligence has evolved from simple rule-based systems to sophisticated neural networks capable of learning from vast amounts of data. Modern AI can recognize images, understand natural language, and even generate creative content. These advances are transforming industries from healthcare to transportation.',
      'The internet began as ARPANET in 1969, connecting just four computers at research institutions. Today, billions of devices are interconnected, enabling instant communication across the globe. This network has fundamentally changed how we access information, conduct business, and maintain relationships.',
      'Quantum computing harnesses the principles of quantum mechanics to process information in fundamentally new ways. Unlike classical computers that use bits representing 0 or 1, quantum computers use qubits that can exist in multiple states simultaneously, potentially solving problems impossible for traditional computers.',
      'Blockchain technology creates decentralized, immutable records of transactions. Originally developed for Bitcoin, blockchain has applications in supply chain management, voting systems, and smart contracts. Its distributed nature eliminates the need for central authorities while maintaining security and transparency.',
      'Renewable energy technologies are rapidly advancing, with solar and wind power becoming increasingly cost-competitive with fossil fuels. Battery technology improvements are addressing the challenge of energy storage, while smart grids are optimizing distribution. These innovations are crucial for addressing climate change.',
    ],
  },
  {
    id: 'general',
    name: 'General Knowledge',
    description: 'Expand your knowledge across various topics',
    icon: '📚',
    paragraphs: [
      'The Great Wall of China stretches over 13,000 miles and was built over many centuries by various Chinese dynasties. Contrary to popular belief, it is not visible from the Moon with the naked eye. The wall was primarily built for defense and border control, with watchtowers allowing signals to be sent across great distances.',
      'The invention of the printing press by Johannes Gutenberg around 1440 revolutionized the spread of knowledge. For the first time, books could be mass-produced rather than hand-copied. This technology accelerated the Renaissance and Reformation by making information accessible to a broader audience.',
      'The deepest part of the ocean, the Mariana Trench, reaches depths of nearly seven miles. The pressure at these depths is over 1,000 times greater than at sea level. Despite these extreme conditions, life exists even in the deepest parts of the ocean, including unique organisms adapted to high pressure and complete darkness.',
      'The human brain contains approximately 86 billion neurons, each connected to thousands of others. This network enables thought, memory, emotion, and consciousness. Despite centuries of study, much about the brain remains mysterious, including the exact nature of consciousness itself.',
      'The Apollo 11 mission in 1969 achieved the first human Moon landing, with Neil Armstrong taking the historic first steps. The astronauts returned with 47.5 pounds of lunar samples. This achievement represented the culmination of the Space Race and demonstrated unprecedented technological capability.',
    ],
  },
  {
    id: 'history',
    name: 'History',
    description: 'Learn from events that shaped our world',
    icon: '🏛️',
    paragraphs: [
      'The Renaissance, beginning in Italy around the 14th century, marked a profound cultural rebirth following the Middle Ages. Artists like Leonardo da Vinci and Michelangelo created masterpieces that still inspire today. This period saw advances in art, science, and philosophy that fundamentally shaped Western civilization.',
      'The Industrial Revolution transformed society from agrarian to industrial, beginning in Britain in the late 18th century. Steam power, mechanized manufacturing, and new transportation methods increased productivity dramatically. This period brought unprecedented wealth but also challenging social conditions for many workers.',
      'Ancient Egypt developed one of the earliest and most influential civilizations along the Nile River. The Egyptians created hieroglyphic writing, built massive pyramids, and developed sophisticated medical practices. Their culture influenced neighboring civilizations and continues to fascinate people today.',
      'World War II, lasting from 1939 to 1945, involved most of the worlds nations in the deadliest conflict in history. The war led to the development of nuclear weapons, the establishment of the United Nations, and the beginning of the Cold War. Its impact on global politics continues to this day.',
      'The Civil Rights Movement in the United States, particularly in the 1950s and 1960s, fought against racial segregation and discrimination. Leaders like Martin Luther King Jr. advocated for equality through nonviolent protest. The movement achieved significant legislative victories and inspired similar movements worldwide.',
    ],
  },
  {
    id: 'science',
    name: 'Science',
    description: 'Explore the laws that govern our universe',
    icon: '🔬',
    paragraphs: [
      'Einstein\'s theory of relativity fundamentally changed our understanding of space, time, and gravity. Special relativity showed that time passes differently for observers moving at different speeds. General relativity revealed that gravity results from the curvature of spacetime caused by mass and energy.',
      'The periodic table, developed by Dmitri Mendeleev in 1869, organizes all known elements by their atomic number and chemical properties. This arrangement allowed Mendeleev to predict the existence of undiscovered elements. Today, the table contains 118 confirmed elements, from hydrogen to oganesson.',
      'Climate change results from increased greenhouse gases trapping heat in the atmosphere. Carbon dioxide levels have risen dramatically since the Industrial Revolution, primarily from burning fossil fuels. Scientists predict significant impacts including rising sea levels, more extreme weather, and ecosystem disruption.',
      'The Big Bang theory describes the origin of the universe approximately 13.8 billion years ago. All matter and energy were once concentrated in an extremely hot, dense point. The universe has been expanding and cooling ever since, forming galaxies, stars, and eventually planets.',
      'Newton\'s laws of motion laid the foundation for classical mechanics. The first law states that objects maintain their motion unless acted upon by a force. The second law relates force, mass, and acceleration. The third law states that every action has an equal and opposite reaction.',
    ],
  },
];

// Export all lessons
export const allLessons = [...beginnerLessons, ...intermediateLessons, ...advancedLessons];
